# Generated by Django 4.0.3 on 2022-03-11 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['travel_time'], 'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.RenameField(
            model_name='route',
            old_name='travel_times',
            new_name='travel_time',
        ),
    ]
